Add support for 10or G (G)
msm8953-mainline/lk2nd pull request #67
Opened 2024-04-11 18:27 UTC by MarvelMathesh

Adhere to the officially rebranded name.

Adjust memory allocation for the pstore logs.

Use the touchscreen-compatible support to associate the Goodix GT917D touchscreen with panels Ilitek ili7807 and Focaltech ft5406 with panel Himax hx8399c.

2024-05-11 15:59 UTC, barni2000 commented
Hi @MarvelMathesh,

Do you planed mainlining the device?
Maybe better to wait together all the PRs what are related to the device.

2024-05-14 03:44 UTC, MarvelMathesh commented
yes, I have plan to mainline the device

2024-05-14 21:38 UTC, barni2000 requested changes

2024-05-14 21:38 UTC, barni2000 commented on dts/msm8953-10or-G.dts
> +				compatible = "10or,hx8399c_auo";
```suggestion
				compatible = "10or,g-hx8399c-auo";
```

2024-05-14 21:38 UTC, barni2000 commented on dts/msm8953-10or-G.dts
> +				compatible = "10or,ili7807d_djn";
```suggestion
				compatible = "10or,g-ili7807d-djn";
```

2024-05-14 21:38 UTC, barni2000 commented on dts/msm8953-10or-G.dts
> +				compatible = "10or,ili7807d_djn_auo";
```suggestion
				compatible = "10or,g-ili7807d-djn-auo";
```

2024-05-17 23:08 UTC, barni2000 commented on dts/rules.mk
> +	$(LOCAL_DIR)/msm8953-10or-G.dtb \
```suggestion
	$(LOCAL_DIR)/msm8953-10or-g.dtb \
```

2024-05-18 09:40 UTC, barni2000 commented
Pleas don't forget to rename the file name also otherwise it  seems LGTM. It will be merged when you open MRs for kernel and for panel-configs.

2024-05-18 10:04 UTC, MarvelMathesh commented
I think it is fine now

2024-06-21 18:41 UTC, M0Rf30 commented
@barni2000 what about this and the related PR on the kernel?

2024-06-21 18:42 UTC, M0Rf30 approved these changes

2024-06-21 19:27 UTC, merged